table MS
	lineageTag: 8c65c4da-9d4f-4bf3-aaa2-5c499400da42

	column 'Sl. No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e65b0d0e-0336-4c55-af2b-702e432e3d03
		summarizeBy: none
		sourceColumn: Sl. No

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Date (DD/MM/YY)'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: ea6c1ee9-2203-41fe-b527-4560d805f12c
		summarizeBy: none
		sourceColumn: Date (DD/MM/YY)

		variation Variation
			isDefault
			relationship: 20b68bab-8055-479c-8ab7-fb4959162054
			defaultHierarchy: LocalDateTable_4546127c-a42c-4536-8baa-471d571a97ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Plant
		dataType: string
		lineageTag: e19f5b8a-b336-4a62-abbf-20c94e0719da
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Planned Prod (Klbs or MT-NTR)'
		dataType: int64
		formatString: 0
		lineageTag: 8c9a0476-c0d2-4767-b804-6c0380d68642
		summarizeBy: none
		sourceColumn: Planned Prod (Klbs or MT-NTR)

		annotation SummarizationSetBy = User

	column 'Act Prod Amt (Klbs or MT-NTR)'
		dataType: int64
		formatString: 0
		lineageTag: 25c3bee5-6a84-481f-a3a8-5e27a1b949bb
		summarizeBy: none
		sourceColumn: Act Prod Amt (Klbs or MT-NTR)

		annotation SummarizationSetBy = User

	column 'OEE (Net) %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e36ad7a7-7c4f-4855-b0ec-fbbe42ded560
		summarizeBy: none
		sourceColumn: OEE (Net) %

		annotation SummarizationSetBy = User

	column 'Trouble DT %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 450e83f8-81f0-4263-a33f-aafd70a415f6
		summarizeBy: none
		sourceColumn: Trouble DT %

		annotation SummarizationSetBy = User

	column 'Quality %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2b6b03fc-d704-4881-ba5b-841808003806
		summarizeBy: none
		sourceColumn: Quality %

		annotation SummarizationSetBy = User

	column 'Yield %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9d6db1fc-2fbf-40e1-b2a3-74ea96813464
		summarizeBy: none
		sourceColumn: Yield %

		annotation SummarizationSetBy = User

	column FY-
		dataType: int64
		formatString: 0
		lineageTag: 25c4d205-7598-40fd-9cac-b3cb79f3dc6d
		summarizeBy: none
		sourceColumn: FY-

		annotation SummarizationSetBy = User

	column 'FY Q-'
		dataType: int64
		formatString: 0
		lineageTag: cf239aea-13cb-4948-9145-f747551f418f
		summarizeBy: none
		sourceColumn: FY Q-

		annotation SummarizationSetBy = User

	partition MS = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\prabhu.ramachandran\OneDrive - Kaneka North America LLC\PMO\Project Execution\Active Projects\Operations & Maintenance\Production KPI\2025_Production Performance KPI (Power BI).xlsx"), null, true),
				    MS_Sheet = Source{[Item="MS",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(MS_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sl. No", Int64.Type}, {"Date (DD/MM/YY)", type date}, {"Date (MM-YY)", type date}, {"Plant", type text}, {"Planned Prod (Klbs or MT-NTR)", Int64.Type}, {"Act Prod Amt (Klbs or MT-NTR)", Int64.Type}, {"OEE (Net) %", type number}, {"Trouble DT %", type number}, {"Quality %", type number}, {"Yield %", type number}, {"FY-", Int64.Type}, {"FY Q-", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"OEE (Net) %", Percentage.Type}, {"Trouble DT %", Percentage.Type}, {"Quality %", Percentage.Type}, {"Yield %", Percentage.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Date (MM-YY)"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

