table NTR
	lineageTag: 3b5153ef-5e31-4582-bb61-853377309967

	column 'Sl. No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f9a107b-3b39-4a4f-98b4-80b14441a1d6
		summarizeBy: none
		sourceColumn: Sl. No

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Date (DD/MM/YY)'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 805c351e-e251-4e1d-b0c8-f6aeb31a05f1
		summarizeBy: none
		sourceColumn: Date (DD/MM/YY)

		variation Variation
			isDefault
			relationship: beef6d43-037c-4b66-a152-972998e764c5
			defaultHierarchy: LocalDateTable_19301cd2-cf02-484c-84e5-e5d862a5273c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Plant
		dataType: string
		lineageTag: a54b6ca8-a6d4-481b-81d4-e0f095bb691f
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Planned Prod (Klbs or MT-NTR)'
		dataType: int64
		formatString: 0.0
		lineageTag: 444e2513-3e44-4675-abb6-6cfd86460167
		summarizeBy: none
		sourceColumn: Planned Prod (Klbs or MT-NTR)

		annotation SummarizationSetBy = User

	column 'Act Prod Amt (Klbs or MT-NTR)'
		dataType: int64
		formatString: 0.0
		lineageTag: e15d3cac-3bfa-4e55-a377-d65b12acb228
		summarizeBy: none
		sourceColumn: Act Prod Amt (Klbs or MT-NTR)

		annotation SummarizationSetBy = User

	column 'OEE (Net) %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7eb1f762-e8ef-4a9d-a6e4-54a6f3634a9d
		summarizeBy: none
		sourceColumn: OEE (Net) %

		annotation SummarizationSetBy = User

	column 'Trouble DT %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e854f9e9-62d7-4969-82eb-2404cb9ea8af
		summarizeBy: none
		sourceColumn: Trouble DT %

		annotation SummarizationSetBy = User

	column 'Quality %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 141fa025-e65f-4421-9ce3-1791f549d24a
		summarizeBy: none
		sourceColumn: Quality %

		annotation SummarizationSetBy = User

	column 'Yield %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 41e905dc-e69d-4ec4-9066-597c53cf1d32
		summarizeBy: none
		sourceColumn: Yield %

		annotation SummarizationSetBy = User

	column FY-
		dataType: int64
		formatString: 0
		lineageTag: 29ac38da-8f39-46e7-ab4e-697fb5ab28c7
		summarizeBy: none
		sourceColumn: FY-

		annotation SummarizationSetBy = User

	column 'FY Q-'
		dataType: int64
		formatString: 0
		lineageTag: 2bef8c55-e5ce-46e6-bb6b-688316469dff
		summarizeBy: none
		sourceColumn: FY Q-

		annotation SummarizationSetBy = User

	partition NTR = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\prabhu.ramachandran\OneDrive - Kaneka North America LLC\PMO\Project Execution\Active Projects\Operations & Maintenance\Production KPI\2025_Production Performance KPI (Power BI).xlsx"), null, true),
				    NTR_Sheet = Source{[Item="NTR",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(NTR_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sl. No", Int64.Type}, {"Date (DD/MM/YY)", type date}, {"Date (MM-YY)", type date}, {"Plant", type text}, {"Planned Prod (Klbs or MT-NTR)", Int64.Type}, {"Act Prod Amt (Klbs or MT-NTR)", Int64.Type}, {"OEE (Net) %", Int64.Type}, {"Trouble DT %", Int64.Type}, {"Quality %", type number}, {"Yield %", type number}, {"FY-", Int64.Type}, {"FY Q-", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"OEE (Net) %", Percentage.Type}, {"Trouble DT %", Percentage.Type}, {"Quality %", Percentage.Type}, {"Yield %", Percentage.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Date (MM-YY)"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

